In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\hp\miniconda3\lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\miniconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\miniconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\miniconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\miniconda3\lib\site-packages (from requests) (2025.8.3)

In [2]:
#API REQUESTS

In [3]:
API_KEY ="hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS"

import requests

url = f"https://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-01&end_date=2024-01-07&api_key={API_KEY}"

response = requests.get(url)    #sends the request and gets NASA's response back.

response

In [4]:
data = response.json()   #converts NASA's raw response into a Python dictionary
data

{'links': {'next': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-07&end_date=2024-01-13&detailed=false&api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS',
  'previous': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2023-12-26&end_date=2024-01-01&detailed=false&api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS',
  'self': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-01&end_date=2024-01-07&detailed=false&api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
 'element_count': 45,
 'near_earth_objects': {'2024-01-02': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '2415949',
    'neo_reference_id': '2415949',
    'name': '415949 (2001 XY10)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949',
    'absolute_magnitude_h': 19.37,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883,
      'estimated_diameter_max': 0.7944013596},
     'meters': {'estimated_diameter_min': 355.267088298,
      'estimated_diameter_max': 794.4013596028},
     'miles': {'estimated_diameter_min': 0.2207526659,
      'estimated_diameter_max': 0.4936179672},
     'feet': {'estimated_diameter_min': 1165.5744739718,
      'estimated_diameter_max': 2606.3037566394}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 13:14',
      'epoch_date_close_approach': 1704201240000,
      'relative_velocity': {'kilometers_per_second': '15.8905264223',
       'kilometers_per_hour': '57205.8951204341',
       'miles_per_hour': '35545.5185541386'},
      'miss_distance': {'astronomical': '0.3372535274',
       'lunar': '131.1916221586',
       'kilometers': '50452409.349026638',
       'miles': '31349673.4658100844'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3160747',
    'neo_reference_id': '3160747',
    'name': '(2003 SR84)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747',
    'absolute_magnitude_h': 26.0,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462,
      'estimated_diameter_max': 0.0375007522},
     'meters': {'estimated_diameter_min': 16.7708462163,
      'estimated_diameter_max': 37.5007521798},
     'miles': {'estimated_diameter_min': 0.0104209175,
      'estimated_diameter_max': 0.0233018799},
     'feet': {'estimated_diameter_min': 55.0224631002,
      'estimated_diameter_max': 123.0339677816}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 22:45',
      'epoch_date_close_approach': 1704235500000,
      'relative_velocity': {'kilometers_per_second': '10.7191818981',
       'kilometers_per_hour': '38589.054833182',
       'miles_per_hour': '23977.7379878735'},
      'miss_distance': {'astronomical': '0.1323425924',
       'lunar': '51.4812684436',
       'kilometers': '19798169.933318188',
       'miles': '12302012.3446714744'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3309828?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3309828',
    'neo_reference_id': '3309828',
    'name': '(2005 YQ96)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3309828',
    'absolute_magnitude_h': 20.62,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1997813652,
      'estimated_diameter_max': 0.4467247133},
     'meters': {'estimated_diameter_min': 199.78136523,
      'estimated_diameter_max': 446.7247132921},
     'miles': {'estimated_diameter_min': 0.1241383467,
      'estimated_diameter_max': 0.2775817818},
     'feet': {'estimated_diameter_min': 655.4506943013,
      'estimated_diameter_max': 1465.6323083572}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 19:42',
      'epoch_date_close_approach': 1704224520000,
      'relative_velocity': {'kilometers_per_second': '15.6702817644',
       'kilometers_per_hour': '56413.0143519451',
       'miles_per_hour': '35052.8532788517'},
      'miss_distance': {'astronomical': '0.1670126223',
       'lunar': '64.9679100747',
       'kilometers': '24984732.559194501',
       'miles': '15524792.9180700738'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3457842?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3457842',
    'neo_reference_id': '3457842',
    'name': '(2009 HC21)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3457842',
    'absolute_magnitude_h': 22.1,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1010543415,
      'estimated_diameter_max': 0.2259643771},
     'meters': {'estimated_diameter_min': 101.054341542,
      'estimated_diameter_max': 225.9643771094},
     'miles': {'estimated_diameter_min': 0.0627922373,
      'estimated_diameter_max': 0.140407711},
     'feet': {'estimated_diameter_min': 331.5431259047,
      'estimated_diameter_max': 741.3529669956}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 12:06',
      'epoch_date_close_approach': 1704197160000,
      'relative_velocity': {'kilometers_per_second': '6.0808661718',
       'kilometers_per_hour': '21891.1182185894',
       'miles_per_hour': '13602.2895397674'},
      'miss_distance': {'astronomical': '0.4920511029',
       'lunar': '191.4078790281',
       'kilometers': '73609796.924990823',
       'miles': '45739006.8632584374'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3553062?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3553062',
    'neo_reference_id': '3553062',
    'name': '(2010 XA11)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3553062',
    'absolute_magnitude_h': 26.1,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338,
      'estimated_diameter_max': 0.0358129403},
     'meters': {'estimated_diameter_min': 16.0160337979,
      'estimated_diameter_max': 35.8129403019},
     'miles': {'estimated_diameter_min': 0.0099518989,
      'estimated_diameter_max': 0.0222531225},
     'feet': {'estimated_diameter_min': 52.5460443254,
      'estimated_diameter_max': 117.4965270602}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 15:31',
      'epoch_date_close_approach': 1704209460000,
      'relative_velocity': {'kilometers_per_second': '8.7413828775',
       'kilometers_per_hour': '31468.9783588978',
       'miles_per_hour': '19553.5993586163'},
      'miss_distance': {'astronomical': '0.2358022486',
       'lunar': '91.7270747054',
       'kilometers': '35275514.131770482',
       'miles': '21919188.0752253716'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3591616?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3591616',
    'neo_reference_id': '3591616',
    'name': '(2011 YP10)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3591616',
    'absolute_magnitude_h': 23.94,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0433066885,
      'estimated_diameter_max': 0.0968366995},
     'meters': {'estimated_diameter_min': 43.3066885476,
      'estimated_diameter_max': 96.8366994728},
     'miles': {'estimated_diameter_min': 0.0269095204,
      'estimated_diameter_max': 0.0601715168},
     'feet': {'estimated_diameter_min': 142.0823160544,
      'estimated_diameter_max': 317.7057170982}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 12:59',
      'epoch_date_close_approach': 1704200340000,
      'relative_velocity': {'kilometers_per_second': '5.8070023218',
       'kilometers_per_hour': '20905.2083584121',
       'miles_per_hour': '12989.6834935922'},
      'miss_distance': {'astronomical': '0.0704899554',
       'lunar': '27.4205926506',
       'kilometers': '10545147.184234998',
       'miles': '6552450.6191110524'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3608936?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3608936',
    'neo_reference_id': '3608936',
    'name': '(2012 SD22)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3608936',
    'absolute_magnitude_h': 20.05,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2597496533,
      'estimated_diameter_max': 0.580817882},
     'meters': {'estimated_diameter_min': 259.7496533301,
      'estimated_diameter_max': 580.817881978},
     'miles': {'estimated_diameter_min': 0.1614009018,
      'estimated_diameter_max': 0.3609033881},
     'feet': {'estimated_diameter_min': 852.1970526314,
      'estimated_diameter_max': 1905.5705399087}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 13:50',
      'epoch_date_close_approach': 1704203400000,
      'relative_velocity': {'kilometers_per_second': '11.0227943004',
       'kilometers_per_hour': '39682.059481597',
       'miles_per_hour': '24656.8885706623'},
      'miss_distance': {'astronomical': '0.1644228854',
       'lunar': '63.9605024206',
       'kilometers': '24597313.435094098',
       'miles': '15284061.8372026324'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3795154?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3795154',
    'neo_reference_id': '3795154',
    'name': '(2017 YD8)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3795154',
    'absolute_magnitude_h': 21.87,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1123453177,
      'estimated_diameter_max': 0.2512117673},
     'meters': {'estimated_diameter_min': 112.3453176718,
      'estimated_diameter_max': 251.2117672679},
     'miles': {'estimated_diameter_min': 0.0698081224,
      'estimated_diameter_max': 0.156095707},
     'feet': {'estimated_diameter_min': 368.5870120303,
      'estimated_diameter_max': 824.1856145234}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 18:22',
      'epoch_date_close_approach': 1704219720000,
      'relative_velocity': {'kilometers_per_second': '18.9936426332',
       'kilometers_per_hour': '68377.1134793652',
       'miles_per_hour': '42486.8792061089'},
      'miss_distance': {'astronomical': '0.2012574006',
       'lunar': '78.2891288334',
       'kilometers': '30107678.451496722',
       'miles': '18708043.8862378836'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842680?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3842680',
    'neo_reference_id': '3842680',
    'name': '(2019 KK5)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842680',
    'absolute_magnitude_h': 22.79,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0735453089,
      'estimated_diameter_max': 0.1644523102},
     'meters': {'estimated_diameter_min': 73.545308935,
      'estimated_diameter_max': 164.452310205},
     'miles': {'estimated_diameter_min': 0.0456989222,
      'estimated_diameter_max': 0.1021858964},
     'feet': {'estimated_diameter_min': 241.2903913664,
      'estimated_diameter_max': 539.5417174129}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 21:21',
      'epoch_date_close_approach': 1704230460000,
      'relative_velocity': {'kilometers_per_second': '20.8331302779',
       'kilometers_per_hour': '74999.2690004519',
       'miles_per_hour': '46601.6291186419'},
      'miss_distance': {'astronomical': '0.0260972745',
       'lunar': '10.1518397805',
       'kilometers': '3904096.678005315',
       'miles': '2425893.185550747'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2613286?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '2613286',
    'neo_reference_id': '2613286',
    'name': '613286 (2005 YQ96)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2613286',
    'absolute_magnitude_h': 20.63,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1988634532,
      'estimated_diameter_max': 0.4446721997},
     'meters': {'estimated_diameter_min': 198.8634532359,
      'estimated_diameter_max': 444.6721996757},
     'miles': {'estimated_diameter_min': 0.1235679828,
      'estimated_diameter_max': 0.2763064094},
     'feet': {'estimated_diameter_min': 652.4391719144,
      'estimated_diameter_max': 1458.8983395842}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 19:42',
      'epoch_date_close_approach': 1704224520000,
      'relative_velocity': {'kilometers_per_second': '15.6702896005',
       'kilometers_per_hour': '56413.0425616862',
       'miles_per_hour': '35052.8708072878'},
      'miss_distance': {'astronomical': '0.16701304',
       'lunar': '64.96807256',
       'kilometers': '24984795.0462248',
       'miles': '15524831.74571024'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2669051?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '2669051',
    'neo_reference_id': '2669051',
    'name': '669051 (2012 SD22)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2669051',
    'absolute_magnitude_h': 20.08,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2561857545,
      'estimated_diameter_max': 0.5728487619},
     'meters': {'estimated_diameter_min': 256.1857544793,
      'estimated_diameter_max': 572.8487618827},
     'miles': {'estimated_diameter_min': 0.1591863984,
      'estimated_diameter_max': 0.355951608},
     'feet': {'estimated_diameter_min': 840.5044707257,
      'estimated_diameter_max': 1879.4251319352}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 13:50',
      'epoch_date_close_approach': 1704203400000,
      'relative_velocity': {'kilometers_per_second': '11.0227939149',
       'kilometers_per_hour': '39682.0580935237',
       'miles_per_hour': '24656.8877081676'},
      'miss_distance': {'astronomical': '0.1644228604',
       'lunar': '63.9604926956',
       'kilometers': '24597309.695147348',
       'miles': '15284059.5133074824'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False}],
  '2024-01-01': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3724393?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3724393',
    'neo_reference_id': '3724393',
    'name': '(2015 OD22)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3724393',
    'absolute_magnitude_h': 21.21,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.152249185,
      'estimated_diameter_max': 0.3404395273},
     'meters': {'estimated_diameter_min': 152.249185036,
      'estimated_diameter_max': 340.4395272595},
     'miles': {'estimated_diameter_min': 0.0946032284,
      'estimated_diameter_max': 0.2115392495},
     'feet': {'estimated_diameter_min': 499.5052162336,
      'estimated_diameter_max': 1116.9276186141}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-01',
      'close_approach_date_full': '2024-Jan-01 11:58',
      'epoch_date_close_approach': 1704110280000,
      'relative_velocity': {'kilometers_per_second': '25.3931645932',
       'kilometers_per_hour': '91415.3925356518',
       'miles_per_hour': '56801.969878611'},
      'miss_distance': {'astronomical': '0.4372881787',
       'lunar': '170.1051015143',
       'kilometers': '65417380.109699369',
       'miles': '40648475.1053305322'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3797695?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3797695',
    'neo_reference_id': '3797695',
    'name': '(2018 BA)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3797695',
    'absolute_magnitude_h': 25.0,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.02658,
      'estimated_diameter_max': 0.0594346868},
     'meters': {'estimated_diameter_min': 26.58,
      'estimated_diameter_max': 59.4346868419},
     'miles': {'estimated_diameter_min': 0.0165160412,
      'estimated_diameter_max': 0.0369309908},
     'feet': {'estimated_diameter_min': 87.2047272,
      'estimated_diameter_max': 194.9956979785}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-01',
      'close_approach_date_full': '2024-Jan-01 08:13',
      'epoch_date_close_approach': 1704096780000,
      'relative_velocity': {'kilometers_per_second': '16.7051869184',
       'kilometers_per_hour': '60138.6729062958',
       'miles_per_hour': '37367.8326178036'},
      'miss_distance': {'astronomical': '0.3961064439',
       'lunar': '154.0854066771',
       'kilometers': '59256680.300714493',
       'miles': '36820393.7545182834'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3986699?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
    'id': '3986699',
    'neo_reference_id': '3986699',
    'name': '(2020 BC)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3986699',
    'absolute_magnitude_h': 26.2,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0152951935,
      'estimated_diameter_max': 0.0342010925},
     'meters': {'estimated_diameter_min': 15.2951935344,
      'estimated_diameter_max': 34.201092472},
     'miles': {'estimated_diameter_min': 0.0095039897,
      'estimated_diameter_max': 0.021251567},
     'feet': {'estimated_diameter_min': 50.1810827555,
      'estimated_diameter_max': 112.2083122258}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-01',
      'close_approach_date_full': '2024-Jan-01 16:14',
      'epoch_date_close_approach': 1704125640000,
      'relative_velocity': {'kilometers_per_second': '8.3141771772',
       'kilometers_per_hour': '29931.0378379052',
       'miles_per_hour': '18597.9829276695'},
      'miss_distance': {'astronomical': '0.1675870266',
       'lunar': '65.1913533474',
       'kilometers': '25070662.218993342',
       'miles': '15578187.1327464396'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False}],

In [5]:
# Keys in the data

In [6]:
data.keys()        # Will show keys of dict

dict_keys(['links', 'element_count', 'near_earth_objects'])

In [7]:
data["near_earth_objects"].keys()        # Will display keys inside near earth objects

dict_keys(['2024-01-02', '2024-01-01', '2024-01-04', '2024-01-03', '2024-01-06', '2024-01-05', '2024-01-07'])

In [10]:
type(data["near_earth_objects"]["2024-01-02"])

list

In [11]:
len(data["near_earth_objects"]["2024-01-02"])

11

In [12]:
details = data["near_earth_objects"]["2024-01-02"][0]
details

{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
 'id': '2415949',
 'neo_reference_id': '2415949',
 'name': '415949 (2001 XY10)',
 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949',
 'absolute_magnitude_h': 19.37,
 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883,
   'estimated_diameter_max': 0.7944013596},
  'meters': {'estimated_diameter_min': 355.267088298,
   'estimated_diameter_max': 794.4013596028},
  'miles': {'estimated_diameter_min': 0.2207526659,
   'estimated_diameter_max': 0.4936179672},
  'feet': {'estimated_diameter_min': 1165.5744739718,
   'estimated_diameter_max': 2606.3037566394}},
 'is_potentially_hazardous_asteroid': False,
 'close_approach_data': [{'close_approach_date': '2024-01-02',
   'close_approach_date_full': '2024-Jan-02 13:14',
   'epoch_date_close_approach': 1704201240000,
   'relative_velocity': {'kilometers_per_second': '15.8905264223',
    'kilometers_per_hour': '57205.8951204341',
    'miles_per_hour': '35545.5185541386'},
   'miss_distance': {'astronomical': '0.3372535274',
    'lunar': '131.1916221586',
    'kilometers': '50452409.349026638',
    'miles': '31349673.4658100844'},
   'orbiting_body': 'Earth'}],
 'is_sentry_object': False}

In [13]:
details = data["near_earth_objects"]
details

{'2024-01-02': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '2415949',
   'neo_reference_id': '2415949',
   'name': '415949 (2001 XY10)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949',
   'absolute_magnitude_h': 19.37,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883,
     'estimated_diameter_max': 0.7944013596},
    'meters': {'estimated_diameter_min': 355.267088298,
     'estimated_diameter_max': 794.4013596028},
    'miles': {'estimated_diameter_min': 0.2207526659,
     'estimated_diameter_max': 0.4936179672},
    'feet': {'estimated_diameter_min': 1165.5744739718,
     'estimated_diameter_max': 2606.3037566394}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 13:14',
     'epoch_date_close_approach': 1704201240000,
     'relative_velocity': {'kilometers_per_second': '15.8905264223',
      'kilometers_per_hour': '57205.8951204341',
      'miles_per_hour': '35545.5185541386'},
     'miss_distance': {'astronomical': '0.3372535274',
      'lunar': '131.1916221586',
      'kilometers': '50452409.349026638',
      'miles': '31349673.4658100844'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3160747',
   'neo_reference_id': '3160747',
   'name': '(2003 SR84)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747',
   'absolute_magnitude_h': 26.0,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462,
     'estimated_diameter_max': 0.0375007522},
    'meters': {'estimated_diameter_min': 16.7708462163,
     'estimated_diameter_max': 37.5007521798},
    'miles': {'estimated_diameter_min': 0.0104209175,
     'estimated_diameter_max': 0.0233018799},
    'feet': {'estimated_diameter_min': 55.0224631002,
     'estimated_diameter_max': 123.0339677816}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 22:45',
     'epoch_date_close_approach': 1704235500000,
     'relative_velocity': {'kilometers_per_second': '10.7191818981',
      'kilometers_per_hour': '38589.054833182',
      'miles_per_hour': '23977.7379878735'},
     'miss_distance': {'astronomical': '0.1323425924',
      'lunar': '51.4812684436',
      'kilometers': '19798169.933318188',
      'miles': '12302012.3446714744'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3309828?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3309828',
   'neo_reference_id': '3309828',
   'name': '(2005 YQ96)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3309828',
   'absolute_magnitude_h': 20.62,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1997813652,
     'estimated_diameter_max': 0.4467247133},
    'meters': {'estimated_diameter_min': 199.78136523,
     'estimated_diameter_max': 446.7247132921},
    'miles': {'estimated_diameter_min': 0.1241383467,
     'estimated_diameter_max': 0.2775817818},
    'feet': {'estimated_diameter_min': 655.4506943013,
     'estimated_diameter_max': 1465.6323083572}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 19:42',
     'epoch_date_close_approach': 1704224520000,
     'relative_velocity': {'kilometers_per_second': '15.6702817644',
      'kilometers_per_hour': '56413.0143519451',
      'miles_per_hour': '35052.8532788517'},
     'miss_distance': {'astronomical': '0.1670126223',
      'lunar': '64.9679100747',
      'kilometers': '24984732.559194501',
      'miles': '15524792.9180700738'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3457842?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3457842',
   'neo_reference_id': '3457842',
   'name': '(2009 HC21)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3457842',
   'absolute_magnitude_h': 22.1,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1010543415,
     'estimated_diameter_max': 0.2259643771},
    'meters': {'estimated_diameter_min': 101.054341542,
     'estimated_diameter_max': 225.9643771094},
    'miles': {'estimated_diameter_min': 0.0627922373,
     'estimated_diameter_max': 0.140407711},
    'feet': {'estimated_diameter_min': 331.5431259047,
     'estimated_diameter_max': 741.3529669956}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 12:06',
     'epoch_date_close_approach': 1704197160000,
     'relative_velocity': {'kilometers_per_second': '6.0808661718',
      'kilometers_per_hour': '21891.1182185894',
      'miles_per_hour': '13602.2895397674'},
     'miss_distance': {'astronomical': '0.4920511029',
      'lunar': '191.4078790281',
      'kilometers': '73609796.924990823',
      'miles': '45739006.8632584374'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3553062?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3553062',
   'neo_reference_id': '3553062',
   'name': '(2010 XA11)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3553062',
   'absolute_magnitude_h': 26.1,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338,
     'estimated_diameter_max': 0.0358129403},
    'meters': {'estimated_diameter_min': 16.0160337979,
     'estimated_diameter_max': 35.8129403019},
    'miles': {'estimated_diameter_min': 0.0099518989,
     'estimated_diameter_max': 0.0222531225},
    'feet': {'estimated_diameter_min': 52.5460443254,
     'estimated_diameter_max': 117.4965270602}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 15:31',
     'epoch_date_close_approach': 1704209460000,
     'relative_velocity': {'kilometers_per_second': '8.7413828775',
      'kilometers_per_hour': '31468.9783588978',
      'miles_per_hour': '19553.5993586163'},
     'miss_distance': {'astronomical': '0.2358022486',
      'lunar': '91.7270747054',
      'kilometers': '35275514.131770482',
      'miles': '21919188.0752253716'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3591616?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3591616',
   'neo_reference_id': '3591616',
   'name': '(2011 YP10)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3591616',
   'absolute_magnitude_h': 23.94,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0433066885,
     'estimated_diameter_max': 0.0968366995},
    'meters': {'estimated_diameter_min': 43.3066885476,
     'estimated_diameter_max': 96.8366994728},
    'miles': {'estimated_diameter_min': 0.0269095204,
     'estimated_diameter_max': 0.0601715168},
    'feet': {'estimated_diameter_min': 142.0823160544,
     'estimated_diameter_max': 317.7057170982}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 12:59',
     'epoch_date_close_approach': 1704200340000,
     'relative_velocity': {'kilometers_per_second': '5.8070023218',
      'kilometers_per_hour': '20905.2083584121',
      'miles_per_hour': '12989.6834935922'},
     'miss_distance': {'astronomical': '0.0704899554',
      'lunar': '27.4205926506',
      'kilometers': '10545147.184234998',
      'miles': '6552450.6191110524'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3608936?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3608936',
   'neo_reference_id': '3608936',
   'name': '(2012 SD22)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3608936',
   'absolute_magnitude_h': 20.05,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2597496533,
     'estimated_diameter_max': 0.580817882},
    'meters': {'estimated_diameter_min': 259.7496533301,
     'estimated_diameter_max': 580.817881978},
    'miles': {'estimated_diameter_min': 0.1614009018,
     'estimated_diameter_max': 0.3609033881},
    'feet': {'estimated_diameter_min': 852.1970526314,
     'estimated_diameter_max': 1905.5705399087}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 13:50',
     'epoch_date_close_approach': 1704203400000,
     'relative_velocity': {'kilometers_per_second': '11.0227943004',
      'kilometers_per_hour': '39682.059481597',
      'miles_per_hour': '24656.8885706623'},
     'miss_distance': {'astronomical': '0.1644228854',
      'lunar': '63.9605024206',
      'kilometers': '24597313.435094098',
      'miles': '15284061.8372026324'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3795154?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3795154',
   'neo_reference_id': '3795154',
   'name': '(2017 YD8)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3795154',
   'absolute_magnitude_h': 21.87,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1123453177,
     'estimated_diameter_max': 0.2512117673},
    'meters': {'estimated_diameter_min': 112.3453176718,
     'estimated_diameter_max': 251.2117672679},
    'miles': {'estimated_diameter_min': 0.0698081224,
     'estimated_diameter_max': 0.156095707},
    'feet': {'estimated_diameter_min': 368.5870120303,
     'estimated_diameter_max': 824.1856145234}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 18:22',
     'epoch_date_close_approach': 1704219720000,
     'relative_velocity': {'kilometers_per_second': '18.9936426332',
      'kilometers_per_hour': '68377.1134793652',
      'miles_per_hour': '42486.8792061089'},
     'miss_distance': {'astronomical': '0.2012574006',
      'lunar': '78.2891288334',
      'kilometers': '30107678.451496722',
      'miles': '18708043.8862378836'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842680?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3842680',
   'neo_reference_id': '3842680',
   'name': '(2019 KK5)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842680',
   'absolute_magnitude_h': 22.79,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0735453089,
     'estimated_diameter_max': 0.1644523102},
    'meters': {'estimated_diameter_min': 73.545308935,
     'estimated_diameter_max': 164.452310205},
    'miles': {'estimated_diameter_min': 0.0456989222,
     'estimated_diameter_max': 0.1021858964},
    'feet': {'estimated_diameter_min': 241.2903913664,
     'estimated_diameter_max': 539.5417174129}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 21:21',
     'epoch_date_close_approach': 1704230460000,
     'relative_velocity': {'kilometers_per_second': '20.8331302779',
      'kilometers_per_hour': '74999.2690004519',
      'miles_per_hour': '46601.6291186419'},
     'miss_distance': {'astronomical': '0.0260972745',
      'lunar': '10.1518397805',
      'kilometers': '3904096.678005315',
      'miles': '2425893.185550747'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2613286?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '2613286',
   'neo_reference_id': '2613286',
   'name': '613286 (2005 YQ96)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2613286',
   'absolute_magnitude_h': 20.63,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1988634532,
     'estimated_diameter_max': 0.4446721997},
    'meters': {'estimated_diameter_min': 198.8634532359,
     'estimated_diameter_max': 444.6721996757},
    'miles': {'estimated_diameter_min': 0.1235679828,
     'estimated_diameter_max': 0.2763064094},
    'feet': {'estimated_diameter_min': 652.4391719144,
     'estimated_diameter_max': 1458.8983395842}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 19:42',
     'epoch_date_close_approach': 1704224520000,
     'relative_velocity': {'kilometers_per_second': '15.6702896005',
      'kilometers_per_hour': '56413.0425616862',
      'miles_per_hour': '35052.8708072878'},
     'miss_distance': {'astronomical': '0.16701304',
      'lunar': '64.96807256',
      'kilometers': '24984795.0462248',
      'miles': '15524831.74571024'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2669051?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '2669051',
   'neo_reference_id': '2669051',
   'name': '669051 (2012 SD22)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2669051',
   'absolute_magnitude_h': 20.08,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2561857545,
     'estimated_diameter_max': 0.5728487619},
    'meters': {'estimated_diameter_min': 256.1857544793,
     'estimated_diameter_max': 572.8487618827},
    'miles': {'estimated_diameter_min': 0.1591863984,
     'estimated_diameter_max': 0.355951608},
    'feet': {'estimated_diameter_min': 840.5044707257,
     'estimated_diameter_max': 1879.4251319352}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 13:50',
     'epoch_date_close_approach': 1704203400000,
     'relative_velocity': {'kilometers_per_second': '11.0227939149',
      'kilometers_per_hour': '39682.0580935237',
      'miles_per_hour': '24656.8877081676'},
     'miss_distance': {'astronomical': '0.1644228604',
      'lunar': '63.9604926956',
      'kilometers': '24597309.695147348',
      'miles': '15284059.5133074824'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False}],
 '2024-01-01': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3724393?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3724393',
   'neo_reference_id': '3724393',
   'name': '(2015 OD22)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3724393',
   'absolute_magnitude_h': 21.21,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.152249185,
     'estimated_diameter_max': 0.3404395273},
    'meters': {'estimated_diameter_min': 152.249185036,
     'estimated_diameter_max': 340.4395272595},
    'miles': {'estimated_diameter_min': 0.0946032284,
     'estimated_diameter_max': 0.2115392495},
    'feet': {'estimated_diameter_min': 499.5052162336,
     'estimated_diameter_max': 1116.9276186141}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-01',
     'close_approach_date_full': '2024-Jan-01 11:58',
     'epoch_date_close_approach': 1704110280000,
     'relative_velocity': {'kilometers_per_second': '25.3931645932',
      'kilometers_per_hour': '91415.3925356518',
      'miles_per_hour': '56801.969878611'},
     'miss_distance': {'astronomical': '0.4372881787',
      'lunar': '170.1051015143',
      'kilometers': '65417380.109699369',
      'miles': '40648475.1053305322'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3797695?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3797695',
   'neo_reference_id': '3797695',
   'name': '(2018 BA)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3797695',
   'absolute_magnitude_h': 25.0,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.02658,
     'estimated_diameter_max': 0.0594346868},
    'meters': {'estimated_diameter_min': 26.58,
     'estimated_diameter_max': 59.4346868419},
    'miles': {'estimated_diameter_min': 0.0165160412,
     'estimated_diameter_max': 0.0369309908},
    'feet': {'estimated_diameter_min': 87.2047272,
     'estimated_diameter_max': 194.9956979785}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-01',
     'close_approach_date_full': '2024-Jan-01 08:13',
     'epoch_date_close_approach': 1704096780000,
     'relative_velocity': {'kilometers_per_second': '16.7051869184',
      'kilometers_per_hour': '60138.6729062958',
      'miles_per_hour': '37367.8326178036'},
     'miss_distance': {'astronomical': '0.3961064439',
      'lunar': '154.0854066771',
      'kilometers': '59256680.300714493',
      'miles': '36820393.7545182834'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3986699?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3986699',
   'neo_reference_id': '3986699',
   'name': '(2020 BC)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3986699',
   'absolute_magnitude_h': 26.2,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0152951935,
     'estimated_diameter_max': 0.0342010925},
    'meters': {'estimated_diameter_min': 15.2951935344,
     'estimated_diameter_max': 34.201092472},
    'miles': {'estimated_diameter_min': 0.0095039897,
     'estimated_diameter_max': 0.021251567},
    'feet': {'estimated_diameter_min': 50.1810827555,
     'estimated_diameter_max': 112.2083122258}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-01',
     'close_approach_date_full': '2024-Jan-01 16:14',
     'epoch_date_close_approach': 1704125640000,
     'relative_velocity': {'kilometers_per_second': '8.3141771772',
      'kilometers_per_hour': '29931.0378379052',
      'miles_per_hour': '18597.9829276695'},
     'miss_distance': {'astronomical': '0.1675870266',
      'lunar': '65.1913533474',
      'kilometers': '25070662.218993342',
      'miles': '15578187.1327464396'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False}],
 '2024-01-04': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3541505?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
   'id': '3541505',
   'neo_reference_id': '3541505',
   'name': '(2010 PJ)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3541505',
   'absolute_magnitude_h': 22.14,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0992098919,
     'estimated_diameter_max': 0.2218400624},
    'meters': {'estimated_diameter_min': 99.2098919421,
     'estimated_diameter_max': 221.8400624229},
    'miles': {'estimated_diameter_min': 0.0616461498,
     'estimated_diameter_max': 0.1378449814},
    'feet': {'estimated_diameter_min': 325.4917818793,
     'estimated_diameter_max': 727.8217503997}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-04',
     'close_approach_date_full': '2024-Jan-04 13:32',

In [14]:
details = data["near_earth_objects"]["2024-01-02"]
details

[{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '2415949',
  'neo_reference_id': '2415949',
  'name': '415949 (2001 XY10)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949',
  'absolute_magnitude_h': 19.37,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883,
    'estimated_diameter_max': 0.7944013596},
   'meters': {'estimated_diameter_min': 355.267088298,
    'estimated_diameter_max': 794.4013596028},
   'miles': {'estimated_diameter_min': 0.2207526659,
    'estimated_diameter_max': 0.4936179672},
   'feet': {'estimated_diameter_min': 1165.5744739718,
    'estimated_diameter_max': 2606.3037566394}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 13:14',
    'epoch_date_close_approach': 1704201240000,
    'relative_velocity': {'kilometers_per_second': '15.8905264223',
     'kilometers_per_hour': '57205.8951204341',
     'miles_per_hour': '35545.5185541386'},
    'miss_distance': {'astronomical': '0.3372535274',
     'lunar': '131.1916221586',
     'kilometers': '50452409.349026638',
     'miles': '31349673.4658100844'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3160747',
  'neo_reference_id': '3160747',
  'name': '(2003 SR84)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747',
  'absolute_magnitude_h': 26.0,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462,
    'estimated_diameter_max': 0.0375007522},
   'meters': {'estimated_diameter_min': 16.7708462163,
    'estimated_diameter_max': 37.5007521798},
   'miles': {'estimated_diameter_min': 0.0104209175,
    'estimated_diameter_max': 0.0233018799},
   'feet': {'estimated_diameter_min': 55.0224631002,
    'estimated_diameter_max': 123.0339677816}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 22:45',
    'epoch_date_close_approach': 1704235500000,
    'relative_velocity': {'kilometers_per_second': '10.7191818981',
     'kilometers_per_hour': '38589.054833182',
     'miles_per_hour': '23977.7379878735'},
    'miss_distance': {'astronomical': '0.1323425924',
     'lunar': '51.4812684436',
     'kilometers': '19798169.933318188',
     'miles': '12302012.3446714744'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3309828?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3309828',
  'neo_reference_id': '3309828',
  'name': '(2005 YQ96)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3309828',
  'absolute_magnitude_h': 20.62,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1997813652,
    'estimated_diameter_max': 0.4467247133},
   'meters': {'estimated_diameter_min': 199.78136523,
    'estimated_diameter_max': 446.7247132921},
   'miles': {'estimated_diameter_min': 0.1241383467,
    'estimated_diameter_max': 0.2775817818},
   'feet': {'estimated_diameter_min': 655.4506943013,
    'estimated_diameter_max': 1465.6323083572}},
  'is_potentially_hazardous_asteroid': True,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 19:42',
    'epoch_date_close_approach': 1704224520000,
    'relative_velocity': {'kilometers_per_second': '15.6702817644',
     'kilometers_per_hour': '56413.0143519451',
     'miles_per_hour': '35052.8532788517'},
    'miss_distance': {'astronomical': '0.1670126223',
     'lunar': '64.9679100747',
     'kilometers': '24984732.559194501',
     'miles': '15524792.9180700738'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3457842?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3457842',
  'neo_reference_id': '3457842',
  'name': '(2009 HC21)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3457842',
  'absolute_magnitude_h': 22.1,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1010543415,
    'estimated_diameter_max': 0.2259643771},
   'meters': {'estimated_diameter_min': 101.054341542,
    'estimated_diameter_max': 225.9643771094},
   'miles': {'estimated_diameter_min': 0.0627922373,
    'estimated_diameter_max': 0.140407711},
   'feet': {'estimated_diameter_min': 331.5431259047,
    'estimated_diameter_max': 741.3529669956}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 12:06',
    'epoch_date_close_approach': 1704197160000,
    'relative_velocity': {'kilometers_per_second': '6.0808661718',
     'kilometers_per_hour': '21891.1182185894',
     'miles_per_hour': '13602.2895397674'},
    'miss_distance': {'astronomical': '0.4920511029',
     'lunar': '191.4078790281',
     'kilometers': '73609796.924990823',
     'miles': '45739006.8632584374'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3553062?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3553062',
  'neo_reference_id': '3553062',
  'name': '(2010 XA11)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3553062',
  'absolute_magnitude_h': 26.1,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338,
    'estimated_diameter_max': 0.0358129403},
   'meters': {'estimated_diameter_min': 16.0160337979,
    'estimated_diameter_max': 35.8129403019},
   'miles': {'estimated_diameter_min': 0.0099518989,
    'estimated_diameter_max': 0.0222531225},
   'feet': {'estimated_diameter_min': 52.5460443254,
    'estimated_diameter_max': 117.4965270602}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 15:31',
    'epoch_date_close_approach': 1704209460000,
    'relative_velocity': {'kilometers_per_second': '8.7413828775',
     'kilometers_per_hour': '31468.9783588978',
     'miles_per_hour': '19553.5993586163'},
    'miss_distance': {'astronomical': '0.2358022486',
     'lunar': '91.7270747054',
     'kilometers': '35275514.131770482',
     'miles': '21919188.0752253716'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3591616?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3591616',
  'neo_reference_id': '3591616',
  'name': '(2011 YP10)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3591616',
  'absolute_magnitude_h': 23.94,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0433066885,
    'estimated_diameter_max': 0.0968366995},
   'meters': {'estimated_diameter_min': 43.3066885476,
    'estimated_diameter_max': 96.8366994728},
   'miles': {'estimated_diameter_min': 0.0269095204,
    'estimated_diameter_max': 0.0601715168},
   'feet': {'estimated_diameter_min': 142.0823160544,
    'estimated_diameter_max': 317.7057170982}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 12:59',
    'epoch_date_close_approach': 1704200340000,
    'relative_velocity': {'kilometers_per_second': '5.8070023218',
     'kilometers_per_hour': '20905.2083584121',
     'miles_per_hour': '12989.6834935922'},
    'miss_distance': {'astronomical': '0.0704899554',
     'lunar': '27.4205926506',
     'kilometers': '10545147.184234998',
     'miles': '6552450.6191110524'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3608936?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3608936',
  'neo_reference_id': '3608936',
  'name': '(2012 SD22)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3608936',
  'absolute_magnitude_h': 20.05,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2597496533,
    'estimated_diameter_max': 0.580817882},
   'meters': {'estimated_diameter_min': 259.7496533301,
    'estimated_diameter_max': 580.817881978},
   'miles': {'estimated_diameter_min': 0.1614009018,
    'estimated_diameter_max': 0.3609033881},
   'feet': {'estimated_diameter_min': 852.1970526314,
    'estimated_diameter_max': 1905.5705399087}},
  'is_potentially_hazardous_asteroid': True,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 13:50',
    'epoch_date_close_approach': 1704203400000,
    'relative_velocity': {'kilometers_per_second': '11.0227943004',
     'kilometers_per_hour': '39682.059481597',
     'miles_per_hour': '24656.8885706623'},
    'miss_distance': {'astronomical': '0.1644228854',
     'lunar': '63.9605024206',
     'kilometers': '24597313.435094098',
     'miles': '15284061.8372026324'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3795154?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3795154',
  'neo_reference_id': '3795154',
  'name': '(2017 YD8)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3795154',
  'absolute_magnitude_h': 21.87,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1123453177,
    'estimated_diameter_max': 0.2512117673},
   'meters': {'estimated_diameter_min': 112.3453176718,
    'estimated_diameter_max': 251.2117672679},
   'miles': {'estimated_diameter_min': 0.0698081224,
    'estimated_diameter_max': 0.156095707},
   'feet': {'estimated_diameter_min': 368.5870120303,
    'estimated_diameter_max': 824.1856145234}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 18:22',
    'epoch_date_close_approach': 1704219720000,
    'relative_velocity': {'kilometers_per_second': '18.9936426332',
     'kilometers_per_hour': '68377.1134793652',
     'miles_per_hour': '42486.8792061089'},
    'miss_distance': {'astronomical': '0.2012574006',
     'lunar': '78.2891288334',
     'kilometers': '30107678.451496722',
     'miles': '18708043.8862378836'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842680?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '3842680',
  'neo_reference_id': '3842680',
  'name': '(2019 KK5)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842680',
  'absolute_magnitude_h': 22.79,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0735453089,
    'estimated_diameter_max': 0.1644523102},
   'meters': {'estimated_diameter_min': 73.545308935,
    'estimated_diameter_max': 164.452310205},
   'miles': {'estimated_diameter_min': 0.0456989222,
    'estimated_diameter_max': 0.1021858964},
   'feet': {'estimated_diameter_min': 241.2903913664,
    'estimated_diameter_max': 539.5417174129}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 21:21',
    'epoch_date_close_approach': 1704230460000,
    'relative_velocity': {'kilometers_per_second': '20.8331302779',
     'kilometers_per_hour': '74999.2690004519',
     'miles_per_hour': '46601.6291186419'},
    'miss_distance': {'astronomical': '0.0260972745',
     'lunar': '10.1518397805',
     'kilometers': '3904096.678005315',
     'miles': '2425893.185550747'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2613286?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '2613286',
  'neo_reference_id': '2613286',
  'name': '613286 (2005 YQ96)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2613286',
  'absolute_magnitude_h': 20.63,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1988634532,
    'estimated_diameter_max': 0.4446721997},
   'meters': {'estimated_diameter_min': 198.8634532359,
    'estimated_diameter_max': 444.6721996757},
   'miles': {'estimated_diameter_min': 0.1235679828,
    'estimated_diameter_max': 0.2763064094},
   'feet': {'estimated_diameter_min': 652.4391719144,
    'estimated_diameter_max': 1458.8983395842}},
  'is_potentially_hazardous_asteroid': True,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 19:42',
    'epoch_date_close_approach': 1704224520000,
    'relative_velocity': {'kilometers_per_second': '15.6702896005',
     'kilometers_per_hour': '56413.0425616862',
     'miles_per_hour': '35052.8708072878'},
    'miss_distance': {'astronomical': '0.16701304',
     'lunar': '64.96807256',
     'kilometers': '24984795.0462248',
     'miles': '15524831.74571024'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2669051?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
  'id': '2669051',
  'neo_reference_id': '2669051',
  'name': '669051 (2012 SD22)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2669051',
  'absolute_magnitude_h': 20.08,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2561857545,
    'estimated_diameter_max': 0.5728487619},
   'meters': {'estimated_diameter_min': 256.1857544793,
    'estimated_diameter_max': 572.8487618827},
   'miles': {'estimated_diameter_min': 0.1591863984,
    'estimated_diameter_max': 0.355951608},
   'feet': {'estimated_diameter_min': 840.5044707257,
    'estimated_diameter_max': 1879.4251319352}},
  'is_potentially_hazardous_asteroid': True,
  'close_approach_data': [{'close_approach_date': '2024-01-02',
    'close_approach_date_full': '2024-Jan-02 13:50',
    'epoch_date_close_approach': 1704203400000,
    'relative_velocity': {'kilometers_per_second': '11.0227939149',
     'kilometers_per_hour': '39682.0580935237',
     'miles_per_hour': '24656.8877081676'},
    'miss_distance': {'astronomical': '0.1644228604',
     'lunar': '63.9604926956',
     'kilometers': '24597309.695147348',
     'miles': '15284059.5133074824'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False}]

In [15]:
details = data["near_earth_objects"]["2024-01-02"][1]
details

{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=hprRMy318rgpEjqcgt7vhZnFxFaOk7j9v4kbhMlS'},
 'id': '3160747',
 'neo_reference_id': '3160747',
 'name': '(2003 SR84)',
 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747',
 'absolute_magnitude_h': 26.0,
 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462,
   'estimated_diameter_max': 0.0375007522},
  'meters': {'estimated_diameter_min': 16.7708462163,
   'estimated_diameter_max': 37.5007521798},
  'miles': {'estimated_diameter_min': 0.0104209175,
   'estimated_diameter_max': 0.0233018799},
  'feet': {'estimated_diameter_min': 55.0224631002,
   'estimated_diameter_max': 123.0339677816}},
 'is_potentially_hazardous_asteroid': False,
 'close_approach_data': [{'close_approach_date': '2024-01-02',
   'close_approach_date_full': '2024-Jan-02 22:45',
   'epoch_date_close_approach': 1704235500000,
   'relative_velocity': {'kilometers_per_second': '10.7191818981',
    'kilometers_per_hour': '38589.054833182',
    'miles_per_hour': '23977.7379878735'},
   'miss_distance': {'astronomical': '0.1323425924',
    'lunar': '51.4812684436',
    'kilometers': '19798169.933318188',
    'miles': '12302012.3446714744'},
   'orbiting_body': 'Earth'}],
 'is_sentry_object': False}

In [16]:
asteroids_data = []   # Will hold all asteroid datat we extracted

target = 1000   # this is limit of data to be collected

while len(asteroids_data) < target:        # loop will stop ,once it reaches target

      response = requests.get(url)
      data = response.json()
      details = data['near_earth_objects']

      for date, asteroids in details.items():

         for asteroid in asteroids:

              asteroids_data.append(
                  dict (
                    id = asteroid['id'],
                    neo_reference_id = asteroid["neo_reference_id"],
                    name = asteroid['name'],
                    absolute_magnitude_h = asteroid['absolute_magnitude_h'],
                    estimated_diameter_min_km = asteroid["estimated_diameter"]['kilometers']['estimated_diameter_min'],
                    estimated_diameter_max_km = asteroid["estimated_diameter"]['kilometers']['estimated_diameter_max'],
                    is_potentially_hazardous_asteroid = asteroid['is_potentially_hazardous_asteroid'],
                    close_approach_date = asteroid["close_approach_data"][0]['close_approach_date'],
                    relative_velocity_kmph = asteroid["close_approach_data"][0]['relative_velocity']['kilometers_per_hour'],
                    astronomical =  asteroid["close_approach_data"][0]["miss_distance"]["astronomical"],
                    miss_distance_km = asteroid["close_approach_data"][0]["miss_distance"]["kilometers"],
                    miss_distance_lunar = asteroid["close_approach_data"][0]["miss_distance"]["lunar"],
                    orbiting_body = asteroid["close_approach_data"][0]["orbiting_body"]))
                 

              if len(asteroids_data) >= target :
                          break

         if len(asteroids_data) >= target :
                        break
      url = data['links']['next']

asteroids_data

[{'id': '2415949',
  'neo_reference_id': '2415949',
  'name': '415949 (2001 XY10)',
  'absolute_magnitude_h': 19.37,
  'estimated_diameter_min_km': 0.3552670883,
  'estimated_diameter_max_km': 0.7944013596,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '57205.8951204341',
  'astronomical': '0.3372535274',
  'miss_distance_km': '50452409.349026638',
  'miss_distance_lunar': '131.1916221586',
  'orbiting_body': 'Earth'},
 {'id': '3160747',
  'neo_reference_id': '3160747',
  'name': '(2003 SR84)',
  'absolute_magnitude_h': 26.0,
  'estimated_diameter_min_km': 0.0167708462,
  'estimated_diameter_max_km': 0.0375007522,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '38589.054833182',
  'astronomical': '0.1323425924',
  'miss_distance_km': '19798169.933318188',
  'miss_distance_lunar': '51.4812684436',
  'orbiting_body': 'Earth'},
 {'id': '3309828',
  'neo_reference_id': '3309828',
  'name': '(2005 YQ96)',
  'absolute_magnitude_h': 20.62,
  'estimated_diameter_min_km': 0.1997813652,
  'estimated_diameter_max_km': 0.4467247133,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '56413.0143519451',
  'astronomical': '0.1670126223',
  'miss_distance_km': '24984732.559194501',
  'miss_distance_lunar': '64.9679100747',
  'orbiting_body': 'Earth'},
 {'id': '3457842',
  'neo_reference_id': '3457842',
  'name': '(2009 HC21)',
  'absolute_magnitude_h': 22.1,
  'estimated_diameter_min_km': 0.1010543415,
  'estimated_diameter_max_km': 0.2259643771,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '21891.1182185894',
  'astronomical': '0.4920511029',
  'miss_distance_km': '73609796.924990823',
  'miss_distance_lunar': '191.4078790281',
  'orbiting_body': 'Earth'},
 {'id': '3553062',
  'neo_reference_id': '3553062',
  'name': '(2010 XA11)',
  'absolute_magnitude_h': 26.1,
  'estimated_diameter_min_km': 0.0160160338,
  'estimated_diameter_max_km': 0.0358129403,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '31468.9783588978',
  'astronomical': '0.2358022486',
  'miss_distance_km': '35275514.131770482',
  'miss_distance_lunar': '91.7270747054',
  'orbiting_body': 'Earth'},
 {'id': '3591616',
  'neo_reference_id': '3591616',
  'name': '(2011 YP10)',
  'absolute_magnitude_h': 23.94,
  'estimated_diameter_min_km': 0.0433066885,
  'estimated_diameter_max_km': 0.0968366995,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '20905.2083584121',
  'astronomical': '0.0704899554',
  'miss_distance_km': '10545147.184234998',
  'miss_distance_lunar': '27.4205926506',
  'orbiting_body': 'Earth'},
 {'id': '3608936',
  'neo_reference_id': '3608936',
  'name': '(2012 SD22)',
  'absolute_magnitude_h': 20.05,
  'estimated_diameter_min_km': 0.2597496533,
  'estimated_diameter_max_km': 0.580817882,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '39682.059481597',
  'astronomical': '0.1644228854',
  'miss_distance_km': '24597313.435094098',
  'miss_distance_lunar': '63.9605024206',
  'orbiting_body': 'Earth'},
 {'id': '3795154',
  'neo_reference_id': '3795154',
  'name': '(2017 YD8)',
  'absolute_magnitude_h': 21.87,
  'estimated_diameter_min_km': 0.1123453177,
  'estimated_diameter_max_km': 0.2512117673,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '68377.1134793652',
  'astronomical': '0.2012574006',
  'miss_distance_km': '30107678.451496722',
  'miss_distance_lunar': '78.2891288334',
  'orbiting_body': 'Earth'},
 {'id': '3842680',
  'neo_reference_id': '3842680',
  'name': '(2019 KK5)',
  'absolute_magnitude_h': 22.79,
  'estimated_diameter_min_km': 0.0735453089,
  'estimated_diameter_max_km': 0.1644523102,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '74999.2690004519',
  'astronomical': '0.0260972745',
  'miss_distance_km': '3904096.678005315',
  'miss_distance_lunar': '10.1518397805',
  'orbiting_body': 'Earth'},
 {'id': '2613286',
  'neo_reference_id': '2613286',
  'name': '613286 (2005 YQ96)',
  'absolute_magnitude_h': 20.63,
  'estimated_diameter_min_km': 0.1988634532,
  'estimated_diameter_max_km': 0.4446721997,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '56413.0425616862',
  'astronomical': '0.16701304',
  'miss_distance_km': '24984795.0462248',
  'miss_distance_lunar': '64.96807256',
  'orbiting_body': 'Earth'},
 {'id': '2669051',
  'neo_reference_id': '2669051',
  'name': '669051 (2012 SD22)',
  'absolute_magnitude_h': 20.08,
  'estimated_diameter_min_km': 0.2561857545,
  'estimated_diameter_max_km': 0.5728487619,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_kmph': '39682.0580935237',
  'astronomical': '0.1644228604',
  'miss_distance_km': '24597309.695147348',
  'miss_distance_lunar': '63.9604926956',
  'orbiting_body': 'Earth'},
 {'id': '3724393',
  'neo_reference_id': '3724393',
  'name': '(2015 OD22)',
  'absolute_magnitude_h': 21.21,
  'estimated_diameter_min_km': 0.152249185,
  'estimated_diameter_max_km': 0.3404395273,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-01',
  'relative_velocity_kmph': '91415.3925356518',
  'astronomical': '0.4372881787',
  'miss_distance_km': '65417380.109699369',
  'miss_distance_lunar': '170.1051015143',
  'orbiting_body': 'Earth'},
 {'id': '3797695',
  'neo_reference_id': '3797695',
  'name': '(2018 BA)',
  'absolute_magnitude_h': 25.0,
  'estimated_diameter_min_km': 0.02658,
  'estimated_diameter_max_km': 0.0594346868,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-01',
  'relative_velocity_kmph': '60138.6729062958',
  'astronomical': '0.3961064439',
  'miss_distance_km': '59256680.300714493',
  'miss_distance_lunar': '154.0854066771',
  'orbiting_body': 'Earth'},
 {'id': '3986699',
  'neo_reference_id': '3986699',
  'name': '(2020 BC)',
  'absolute_magnitude_h': 26.2,
  'estimated_diameter_min_km': 0.0152951935,
  'estimated_diameter_max_km': 0.0342010925,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-01',
  'relative_velocity_kmph': '29931.0378379052',
  'astronomical': '0.1675870266',
  'miss_distance_km': '25070662.218993342',
  'miss_distance_lunar': '65.1913533474',
  'orbiting_body': 'Earth'},
 {'id': '3541505',
  'neo_reference_id': '3541505',
  'name': '(2010 PJ)',
  'absolute_magnitude_h': 22.14,
  'estimated_diameter_min_km': 0.0992098919,
  'estimated_diameter_max_km': 0.2218400624,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-04',
  'relative_velocity_kmph': '66284.046805343',
  'astronomical': '0.325882928',
  'miss_distance_km': '48751391.89816336',
  'miss_distance_lunar': '126.768458992',
  'orbiting_body': 'Earth'},
 {'id': '3759758',
  'neo_reference_id': '3759758',
  'name': '(2016 SU2)',
  'absolute_magnitude_h': 27.6,
  'estimated_diameter_min_km': 0.0080270317,
  'estimated_diameter_max_km': 0.0179489885,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-04',
  'relative_velocity_kmph': '61645.9178601515',
  'astronomical': '0.1648175282',
  'miss_distance_km': '24656351.157384934',
  'miss_distance_lunar': '64.1140184698',
  'orbiting_body': 'Earth'},
 {'id': '3154493',
  'neo_reference_id': '3154493',
  'name': '(2003 JV14)',
  'absolute_magnitude_h': 21.39,
  'estimated_diameter_min_km': 0.1401376972,
  'estimated_diameter_max_km': 0.3133574171,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '49177.1673871585',
  'astronomical': '0.2621610014',
  'miss_distance_km': '39218727.406507018',
  'miss_distance_lunar': '101.9806295446',
  'orbiting_body': 'Earth'},
 {'id': '3591759',
  'neo_reference_id': '3591759',
  'name': '(2011 YE40)',
  'absolute_magnitude_h': 25.2,
  'estimated_diameter_min_km': 0.0242412481,
  'estimated_diameter_max_km': 0.0542050786,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '47099.8219113461',
  'astronomical': '0.1185645923',
  'miss_distance_km': '17737010.465498401',
  'miss_distance_lunar': '46.1216264047',
  'orbiting_body': 'Earth'},
 {'id': '3595775',
  'neo_reference_id': '3595775',
  'name': '(2012 AB11)',
  'absolute_magnitude_h': 22.32,
  'estimated_diameter_min_km': 0.0913177026,
  'estimated_diameter_max_km': 0.2041925905,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '66101.0085197716',
  'astronomical': '0.2870697327',
  'miss_distance_km': '42945020.553389349',
  'miss_distance_lunar': '111.6701260203',
  'orbiting_body': 'Earth'},
 {'id': '3605578',
  'neo_reference_id': '3605578',
  'name': '(2012 LJ2)',
  'absolute_magnitude_h': 21.7,
  'estimated_diameter_min_km': 0.1214940408,
  'estimated_diameter_max_km': 0.2716689341,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '62605.7918647103',
  'astronomical': '0.4856779711',
  'miss_distance_km': '72656389.982481557',
  'miss_distance_lunar': '188.9287307579',
  'orbiting_body': 'Earth'},
 {'id': '3645001',
  'neo_reference_id': '3645001',
  'name': '(2013 NT11)',
  'absolute_magnitude_h': 19.49,
  'estimated_diameter_min_km': 0.3361669212,
  'estimated_diameter_max_km': 0.7516920875,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '136267.5931308216',
  'astronomical': '0.3878716833',
  'miss_distance_km': '58024777.654994571',
  'miss_distance_lunar': '150.8820848037',
  'orbiting_body': 'Earth'},
 {'id': '3751529',
  'neo_reference_id': '3751529',
  'name': '(2016 GZ215)',
  'absolute_magnitude_h': 21.08,
  'estimated_diameter_min_km': 0.1616422833,
  'estimated_diameter_max_km': 0.3614431336,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '13412.6297084999',
  'astronomical': '0.3169592421',
  'miss_distance_km': '47416427.494974327',
  'miss_distance_lunar': '123.2971451769',
  'orbiting_body': 'Earth'},
 {'id': '3787600',
  'neo_reference_id': '3787600',
  'name': '(2017 UJ2)',
  'absolute_magnitude_h': 30.9,
  'estimated_diameter_min_km': 0.0017561232,
  'estimated_diameter_max_km': 0.0039268108,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '20392.71468415',
  'astronomical': '0.2789034507',
  'miss_distance_km': '41723362.160370009',
  'miss_distance_lunar': '108.4934423223',
  'orbiting_body': 'Earth'},
 {'id': '3789479',
  'neo_reference_id': '3789479',
  'name': '(2017 WQ1)',
  'absolute_magnitude_h': 24.98,
  'estimated_diameter_min_km': 0.0268259417,
  'estimated_diameter_max_km': 0.0599846292,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '77947.7941353121',
  'astronomical': '0.3928589898',
  'miss_distance_km': '58770868.084431726',
  'miss_distance_lunar': '152.8221470322',
  'orbiting_body': 'Earth'},
 {'id': '3837605',
  'neo_reference_id': '3837605',
  'name': '(2019 AE3)',
  'absolute_magnitude_h': 27.4,
  'estimated_diameter_min_km': 0.0088014652,
  'estimated_diameter_max_km': 0.0196806745,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '30643.8908800298',
  'astronomical': '0.219831404',
  'miss_distance_km': '32886309.79750948',
  'miss_distance_lunar': '85.514416156',
  'orbiting_body': 'Earth'},
 {'id': '3986746',
  'neo_reference_id': '3986746',
  'name': '(2020 BG1)',
  'absolute_magnitude_h': 22.08,
  'estimated_diameter_min_km': 0.1019893859,
  'estimated_diameter_max_km': 0.2280551997,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '30660.8552813021',
  'astronomical': '0.4392947647',
  'miss_distance_km': '65717561.101271189',
  'miss_distance_lunar': '170.8856634683',
  'orbiting_body': 'Earth'},
 {'id': '2668499',
  'neo_reference_id': '2668499',
  'name': '668499 (2012 AB11)',
  'absolute_magnitude_h': 22.32,
  'estimated_diameter_min_km': 0.0913177026,
  'estimated_diameter_max_km': 0.2041925905,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_kmph': '66101.008470871',
  'astronomical': '0.2870697328',
  'miss_distance_km': '42945020.568349136',
  'miss_distance_lunar': '111.6701260592',
  'orbiting_body': 'Earth'},
 {'id': '2304640',
  'neo_reference_id': '2304640',
  'name': '304640 (2006 WW1)',
  'absolute_magnitude_h': 19.17,
  'estimated_diameter_min_km': 0.3895426161,
  'estimated_diameter_max_km': 0.8710437698,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '82917.386474944',
  'astronomical': '0.3042250642',
  'miss_distance_km': '45511421.604933254',
  'miss_distance_lunar': '118.3435499738',
  'orbiting_body': 'Earth'},
 {'id': '3102756',
  'neo_reference_id': '3102756',
  'name': '(2002 AO11)',
  'absolute_magnitude_h': 23.05,
  'estimated_diameter_min_km': 0.065246163,
  'estimated_diameter_max_km': 0.1458948557,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '66352.9893943133',
  'astronomical': '0.4011389088',
  'miss_distance_km': '60009526.330604256',
  'miss_distance_lunar': '156.0430355232',
  'orbiting_body': 'Earth'},
 {'id': '3623521',
  'neo_reference_id': '3623521',
  'name': '(2013 AK20)',
  'absolute_magnitude_h': 23.19,
  'estimated_diameter_min_km': 0.0611723235,
  'estimated_diameter_max_km': 0.1367854737,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '33449.0167383958',
  'astronomical': '0.2658726974',
  'miss_distance_km': '39773989.222194538',
  'miss_distance_lunar': '103.4244792886',
  'orbiting_body': 'Earth'},
 {'id': '3630638',
  'neo_reference_id': '3630638',
  'name': '(2013 EU9)',
  'absolute_magnitude_h': 21.66,
  'estimated_diameter_min_km': 0.1237527837,
  'estimated_diameter_max_km': 0.2767196367,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '23244.7020210603',
  'astronomical': '0.4595500589',
  'miss_distance_km': '68747709.969814543',
  'miss_distance_lunar': '178.7649729121',
  'orbiting_body': 'Earth'},
 {'id': '3752775',
  'neo_reference_id': '3752775',
  'name': '(2016 JX5)',
  'absolute_magnitude_h': 26.9,
  'estimated_diameter_min_km': 0.0110803882,
  'estimated_diameter_max_km': 0.0247765013,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '47409.8201474422',
  'astronomical': '0.219641036',
  'miss_distance_km': '32857831.15019332',
  'miss_distance_lunar': '85.440363004',
  'orbiting_body': 'Earth'},
 {'id': '3780672',
  'neo_reference_id': '3780672',
  'name': '(2017 PM26)',
  'absolute_magnitude_h': 21.28,
  'estimated_diameter_min_km': 0.1474195145,
  'estimated_diameter_max_km': 0.3296400556,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '67006.5424308666',
  'astronomical': '0.2157438397',
  'miss_distance_km': '32274818.884741439',
  'miss_distance_lunar': '83.9243536433',
  'orbiting_body': 'Earth'},
 {'id': '3794988',
  'neo_reference_id': '3794988',
  'name': '(2017 YZ1)',
  'absolute_magnitude_h': 20.43,
  'estimated_diameter_min_km': 0.2180494405,
  'estimated_diameter_max_km': 0.4875733714,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '44018.2595059564',
  'astronomical': '0.4823054753',
  'miss_distance_km': '72151871.794217611',
  'miss_distance_lunar': '187.6168298917',
  'orbiting_body': 'Earth'},
 {'id': '2591179',
  'neo_reference_id': '2591179',
  'name': '591179 (2013 EU9)',
  'absolute_magnitude_h': 21.66,
  'estimated_diameter_min_km': 0.1237527837,
  'estimated_diameter_max_km': 0.2767196367,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_kmph': '23244.7048088382',
  'astronomical': '0.4595501104',
  'miss_distance_km': '68747717.674104848',
  'miss_distance_lunar': '178.7649929456',
  'orbiting_body': 'Earth'},
 {'id': '3387092',
  'neo_reference_id': '3387092',
  'name': '(2007 SG11)',
  'absolute_magnitude_h': 22.68,
  'estimated_diameter_min_km': 0.077366861,
  'estimated_diameter_max_km': 0.1729975604,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_kmph': '21130.5453762448',
  'astronomical': '0.279217138',
  'miss_distance_km': '41770289.11229606',
  'miss_distance_lunar': '108.615466682',
  'orbiting_body': 'Earth'},
 {'id': '3655366',
  'neo_reference_id': '3655366',
  'name': '(2013 YD)',
  'absolute_magnitude_h': 23.6,
  'estimated_diameter_min_km': 0.0506471459,
  'estimated_diameter_max_km': 0.1132504611,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_kmph': '95388.94889847',
  'astronomical': '0.4134715606',
  'miss_distance_km': '61854464.771335922',
  'miss_distance_lunar': '160.8404370734',
  'orbiting_body': 'Earth'},
 {'id': '3759280',
  'neo_reference_id': '3759280',
  'name': '(2016 RW19)',
  'absolute_magnitude_h': 20.97,
  'estimated_diameter_min_km': 0.1700415193,
  'estimated_diameter_max_km': 0.3802243961,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_kmph': '55636.6868556782',
  'astronomical': '0.3310608323',
  'miss_distance_km': '49525995.352507201',
  'miss_distance_lunar': '128.7826637647',
  'orbiting_body': 'Earth'},
 {'id': '3795150',
  'neo_reference_id': '3795150',
  'name': '(2017 YA8)',
  'absolute_magnitude_h': 22.33,
  'estimated_diameter_min_km': 0.0908981358,
  'estimated_diameter_max_km': 0.2032544107,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_kmph': '74295.3517022466',
  'astronomical': '0.47281464',
  'miss_distance_km': '70732063.0488168',
  'miss_distance_lunar': '183.92489496',
  'orbiting_body': 'Earth'},
 {'id': '3989198',
  'neo_reference_id': '3989198',
  'name': '(2020 BT8)',
  'absolute_magnitude_h': 22.66,
  'estimated_diameter_min_km': 0.0780827277,
  'estimated_diameter_max_km': 0.1745982871,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_kmph': '32809.7259574529',
  'astronomical': '0.4020460517',
  'miss_distance_km': '60145232.976229879',
  'miss_distance_lunar': '156.3959141113',
  'orbiting_body': 'Earth'},
 {'id': '2199003',
  'neo_reference_id': '2199003',
  'name': '199003 (2005 WJ56)',
  'absolute_magnitude_h': 18.16,
  'estimated_diameter_min_km': 0.620233153,
  'estimated_diameter_max_km': 1.3868834919,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-07',
  'relative_velocity_kmph': '55047.0116924064',
  'astronomical': '0.1995345465',
  'miss_distance_km': '29849943.147815955',
  'miss_distance_lunar': '77.6189385885',
  'orbiting_body': 'Earth'},
 {'id': '3398095',
  'neo_reference_id': '3398095',
  'name': '(2007 YZ)',
  'absolute_magnitude_h': 19.53,
  'estimated_diameter_min_km': 0.3300311834,
  'estimated_diameter_max_km': 0.7379721607,
  'is_potentially_hazardous_asteroid': False,

In [17]:
len(asteroids_data)

1000

## SQL Insertion

In [18]:
import pandas as pd
from sqlalchemy import *

username = 'root'
password = '1234'
host = 'localhost'
port = 3306
database = 'project_db'

# create sqlalchemy engine
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
conn = engine.connect()

In [19]:
import pandas as  pd
df = pd.DataFrame(asteroids_data)
df

,id,neo_reference_id,name,absolute_magnitude_h,estimated_diameter_min_km,estimated_diameter_max_km,is_potentially_hazardous_asteroid,close_approach_date,relative_velocity_kmph,astronomical,miss_distance_km,miss_distance_lunar,orbiting_body
0,2415949,2415949,415949 (2001 XY10),19.37,0.355267,0.794401,False,2024-01-02,57205.8951204341,0.3372535274,50452409.349026638,131.1916221586,Earth
1,3160747,3160747,(2003 SR84),26.00,0.016771,0.037501,False,2024-01-02,38589.054833182,0.1323425924,19798169.933318188,51.4812684436,Earth
2,3309828,3309828,(2005 YQ96),20.62,0.199781,0.446725,True,2024-01-02,56413.0143519451,0.1670126223,24984732.559194501,64.9679100747,Earth
3,3457842,3457842,(2009 HC21),22.10,0.101054,0.225964,False,2024-01-02,21891.1182185894,0.4920511029,73609796.924990823,191.4078790281,Earth
4,3553062,3553062,(2010 XA11),26.10,0.016016,0.035813,False,2024-01-02,31468.9783588978,0.2358022486,35275514.131770482,91.7270747054,Earth
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,54017120,54017120,(2020 KP1),23.10,0.063761,0.142574,False,2024-05-15,60524.1145646626,0.1221396196,18271826.934770252,47.5123120244,Earth
996,2679756,2679756,679756 (2020 KP1),23.13,0.062886,0.140618,False,2024-05-15,60524.0901393242,0.1221395378,18271814.697664486,47.5122802042,Earth
997,3174187,3174187,(2004 BT58),22.19,0.096952,0.216790,False,2024-05-12,64961.5766907038,0.3230078823,48321291.185290701,125.6500662147,Earth
998,3717100,3717100,(2015 HF11),19.28,0.370301,0.828018,False,2024-05-12,67618.9781624372,0.2265233276,33887407.314272212,88.1175744364,Earth
999,3973542,3973542,(2020 AC1),28.39,0.005579,0.012475,False,2024-05-12,18164.5149590046,0.2276362156,34053892.988620772,88.5504878684,Earth

In [20]:
df.columns

Index(['id', 'neo_reference_id', 'name', 'absolute_magnitude_h',
       'estimated_diameter_min_km', 'estimated_diameter_max_km',
       'is_potentially_hazardous_asteroid', 'close_approach_date',
       'relative_velocity_kmph', 'astronomical', 'miss_distance_km',
       'miss_distance_lunar', 'orbiting_body'],
      dtype='object')

In [23]:
df_asteroids = df[['id', 'name', 'absolute_magnitude_h',
       'estimated_diameter_min_km', 'estimated_diameter_max_km',
       'is_potentially_hazardous_asteroid']]
df_asteroids

,id,name,absolute_magnitude_h,estimated_diameter_min_km,estimated_diameter_max_km,is_potentially_hazardous_asteroid
0,2415949,415949 (2001 XY10),19.37,0.355267,0.794401,False
1,3160747,(2003 SR84),26.00,0.016771,0.037501,False
2,3309828,(2005 YQ96),20.62,0.199781,0.446725,True
3,3457842,(2009 HC21),22.10,0.101054,0.225964,False
4,3553062,(2010 XA11),26.10,0.016016,0.035813,False
...,...,...,...,...,...,...
995,54017120,(2020 KP1),23.10,0.063761,0.142574,False
996,2679756,679756 (2020 KP1),23.13,0.062886,0.140618,False
997,3174187,(2004 BT58),22.19,0.096952,0.216790,False
998,3717100,(2015 HF11),19.28,0.370301,0.828018,False
999,3973542,(2020 AC1),28.39,0.005579,0.012475,False

In [24]:
df_asteroids.to_sql("asteroids_table",if_exists= "replace",con = engine, index=False)
df_asteroids

,id,name,absolute_magnitude_h,estimated_diameter_min_km,estimated_diameter_max_km,is_potentially_hazardous_asteroid
0,2415949,415949 (2001 XY10),19.37,0.355267,0.794401,False
1,3160747,(2003 SR84),26.00,0.016771,0.037501,False
2,3309828,(2005 YQ96),20.62,0.199781,0.446725,True
3,3457842,(2009 HC21),22.10,0.101054,0.225964,False
4,3553062,(2010 XA11),26.10,0.016016,0.035813,False
...,...,...,...,...,...,...
995,54017120,(2020 KP1),23.10,0.063761,0.142574,False
996,2679756,679756 (2020 KP1),23.13,0.062886,0.140618,False
997,3174187,(2004 BT58),22.19,0.096952,0.216790,False
998,3717100,(2015 HF11),19.28,0.370301,0.828018,False
999,3973542,(2020 AC1),28.39,0.005579,0.012475,False

In [25]:
df_close_approach = df[["neo_reference_id",'close_approach_date',
       'relative_velocity_kmph', 'astronomical', 'miss_distance_km',
       'miss_distance_lunar', 'orbiting_body']]
df_close_approach

,neo_reference_id,close_approach_date,relative_velocity_kmph,astronomical,miss_distance_km,miss_distance_lunar,orbiting_body
0,2415949,2024-01-02,57205.8951204341,0.3372535274,50452409.349026638,131.1916221586,Earth
1,3160747,2024-01-02,38589.054833182,0.1323425924,19798169.933318188,51.4812684436,Earth
2,3309828,2024-01-02,56413.0143519451,0.1670126223,24984732.559194501,64.9679100747,Earth
3,3457842,2024-01-02,21891.1182185894,0.4920511029,73609796.924990823,191.4078790281,Earth
4,3553062,2024-01-02,31468.9783588978,0.2358022486,35275514.131770482,91.7270747054,Earth
...,...,...,...,...,...,...,...
995,54017120,2024-05-15,60524.1145646626,0.1221396196,18271826.934770252,47.5123120244,Earth
996,2679756,2024-05-15,60524.0901393242,0.1221395378,18271814.697664486,47.5122802042,Earth
997,3174187,2024-05-12,64961.5766907038,0.3230078823,48321291.185290701,125.6500662147,Earth
998,3717100,2024-05-12,67618.9781624372,0.2265233276,33887407.314272212,88.1175744364,Earth
999,3973542,2024-05-12,18164.5149590046,0.2276362156,34053892.988620772,88.5504878684,Earth

In [26]:
df_close_approach.to_sql("close_approach_table",if_exists= "replace",con = engine, index=False)
df_close_approach

,neo_reference_id,close_approach_date,relative_velocity_kmph,astronomical,miss_distance_km,miss_distance_lunar,orbiting_body
0,2415949,2024-01-02,57205.8951204341,0.3372535274,50452409.349026638,131.1916221586,Earth
1,3160747,2024-01-02,38589.054833182,0.1323425924,19798169.933318188,51.4812684436,Earth
2,3309828,2024-01-02,56413.0143519451,0.1670126223,24984732.559194501,64.9679100747,Earth
3,3457842,2024-01-02,21891.1182185894,0.4920511029,73609796.924990823,191.4078790281,Earth
4,3553062,2024-01-02,31468.9783588978,0.2358022486,35275514.131770482,91.7270747054,Earth
...,...,...,...,...,...,...,...
995,54017120,2024-05-15,60524.1145646626,0.1221396196,18271826.934770252,47.5123120244,Earth
996,2679756,2024-05-15,60524.0901393242,0.1221395378,18271814.697664486,47.5122802042,Earth
997,3174187,2024-05-12,64961.5766907038,0.3230078823,48321291.185290701,125.6500662147,Earth
998,3717100,2024-05-12,67618.9781624372,0.2265233276,33887407.314272212,88.1175744364,Earth
999,3973542,2024-05-12,18164.5149590046,0.2276362156,34053892.988620772,88.5504878684,Earth

In [27]:
pd.read_sql("SELECT * FROM asteroids_table", con = engine)

,id,name,absolute_magnitude_h,estimated_diameter_min_km,estimated_diameter_max_km,is_potentially_hazardous_asteroid
0,2415949,415949 (2001 XY10),19.37,0.355267,0.794401,0
1,3160747,(2003 SR84),26.00,0.016771,0.037501,0
2,3309828,(2005 YQ96),20.62,0.199781,0.446725,1
3,3457842,(2009 HC21),22.10,0.101054,0.225964,0
4,3553062,(2010 XA11),26.10,0.016016,0.035813,0
...,...,...,...,...,...,...
995,54017120,(2020 KP1),23.10,0.063761,0.142574,0
996,2679756,679756 (2020 KP1),23.13,0.062886,0.140618,0
997,3174187,(2004 BT58),22.19,0.096952,0.216790,0
998,3717100,(2015 HF11),19.28,0.370301,0.828018,0
999,3973542,(2020 AC1),28.39,0.005579,0.012475,0

In [28]:
pd.read_sql("show tables;", con = engine)

   Tables_in_project_db
0       asteroids_table
1  close_approach_table

In [29]:
# 1. Count how many times each asteroid has approached Earth

select_query = """
SELECT 
    ca.neo_reference_id,
    COUNT(*) AS approach_count
FROM close_approach_table ca
GROUP BY ca.neo_reference_id
ORDER BY approach_count DESC;
"""

df1 = pd.read_sql(select_query, engine)
df1

    neo_reference_id  approach_count
0            3092124               3
1            3973542               3
2            3440320               3
3            3255980               3
4            2612856               3
..               ...             ...
848          3617959               1
849          3772992               1
850          3791307               1
851         54017120               1
852          2679756               1

[853 rows x 2 columns]

In [30]:
# 2.Average velocity of each asteroid over multiple approaches

select_query = """
SELECT 
    AVG(relative_velocity_kmph) AS avg_velocity_kmph
FROM close_approach_table
GROUP BY neo_reference_id
ORDER BY avg_velocity_kmph DESC;
"""

df2 = pd.read_sql(select_query, engine)
df2
df2.style.hide(axis="index")

In [31]:
# 3. List top 10 fastest asteroids'

select_query = """
SELECT 
    AVG(relative_velocity_kmph) AS avg_velocity_kmph
FROM close_approach_table
GROUP BY neo_reference_id
ORDER BY avg_velocity_kmph DESC LIMIT 10;
"""

df3 = pd.read_sql(select_query, engine)
df3
df3.style.hide(axis="index")

#4Find potentially hazardous asteroids that have approached Earth more than 3 times
select_query = """
SELECT 
    a.name,
    COUNT(*) AS approach_count
FROM asteroids_table a
JOIN close_approach_table ca
    ON a.id = ca.neo_reference_id
WHERE a.is_potentially_hazardous_asteroid = 1
GROUP BY a.id, a.name
HAVING COUNT(*) > 3
ORDER BY approach_count DESC;
"""

df4 = pd.read_sql(select_query, engine)
df4
df4.style.hide(axis="index")

In [32]:
#5. Find the month with the most asteroid approaches
select_query = """
SELECT DATE_FORMAT(close_approach_date, '%%Y-%%m') AS approach_month, 
       COUNT(*) AS approach_count
FROM close_approach_table
GROUP BY approach_month
ORDER BY approach_count DESC
LIMIT 1;
"""

df5 = pd.read_sql(select_query, engine)
df5 = df5.reset_index(drop=True)
df5.style.hide(axis="index")

In [33]:
# 6. Get the asteroid with the fastest ever approach speed 

select_query = """
SELECT a.name, ca.relative_velocity_kmph
FROM close_approach_table ca
JOIN (SELECT DISTINCT id, name FROM asteroids_table) a
    ON ca.neo_reference_id = a.id
ORDER BY ca.relative_velocity_kmph DESC
LIMIT 1;
"""

df4 = pd.read_sql(select_query, engine)
df4
df4.style.hide(axis="index")

In [34]:
# 7.Sort asteroids by maximum estimated diameter (descending)

select_query = """
SELECT name, estimated_diameter_max_km
FROM asteroids_table
ORDER BY estimated_diameter_max_km DESC;
"""

df4 = pd.read_sql(select_query, engine)
df4
df4.style.hide(axis="index")

In [35]:
#8. Asteroid whose closest approach is getting nearer over time

select_query = """
SELECT neo_reference_id, close_approach_date, miss_distance_km
FROM close_approach_table
ORDER BY neo_reference_id, close_approach_date;
"""

df4 = pd.read_sql(select_query, engine)
df4
df4.style.hide(axis="index")

In [36]:
# 9. Name, date, and miss distance of each asteroid's closest approach"

select_query = """
SELECT a.name, ca.close_approach_date, ca.miss_distance_km
FROM close_approach_table ca
JOIN (SELECT DISTINCT id, name FROM asteroids_table) a
    ON ca.neo_reference_id = a.id
WHERE ca.miss_distance_km = (
    SELECT MIN(ca2.miss_distance_km)
    FROM close_approach_table ca2
    WHERE ca2.neo_reference_id = ca.neo_reference_id
)
ORDER BY ca.miss_distance_km ASC;
"""

df4 = pd.read_sql(select_query, engine)
df4
df4.style.hide(axis="index")

In [37]:
# 10. Asteroids that approached Earth with velocity > 50,000 km/h"

select_query = """
SELECT DISTINCT a.name, ca.relative_velocity_kmph, ca.close_approach_date
FROM close_approach_table ca
JOIN (SELECT DISTINCT id, name FROM asteroids_table) a
    ON ca.neo_reference_id = a.id
WHERE ca.relative_velocity_kmph > 50000
ORDER BY ca.relative_velocity_kmph DESC;
"""

df4 = pd.read_sql(select_query, engine)
df4
df4.style.hide(axis="index")

In [38]:
# "11. Count how many approaches happened per month":

select_query = """
SELECT DATE_FORMAT(close_approach_date, '%%Y-%%m') AS approach_month, 
       COUNT(*) AS approach_count
FROM close_approach_table
GROUP BY approach_month
ORDER BY approach_month;
"""

df4 = pd.read_sql(select_query, engine)
df4
df4 = df4.reset_index(drop=True)

In [39]:
# "12. Asteroid with the highest brightness (lowest magnitude value)"

select_query = """
SELECT DISTINCT  name, absolute_magnitude_h
FROM asteroids_table
ORDER BY absolute_magnitude_h ASC
LIMIT 1;
"""

df5 = pd.read_sql(select_query, engine)
df5 = df5.reset_index(drop=True)
df5.style.hide(axis="index")

In [40]:
#"13. Get number of hazardous vs non-hazardous asteroids"
select_query = """
SELECT COUNT(is_potentially_hazardous_asteroid)
FROM asteroids_table
GROUP BY is_potentially_hazardous_asteroid;
"""

df5 = pd.read_sql(select_query, engine)
df5
df5.style.hide(axis="index")

In [41]:
# "14. Asteroids that passed closer than the Moon (< 1 LD)"

select_query = """
SELECT a.name, ca.close_approach_date, ca.miss_distance_lunar, ca.miss_distance_km
FROM close_approach_table ca
JOIN (SELECT DISTINCT id, name FROM asteroids_table) a
    ON ca.neo_reference_id = a.id
WHERE ca.miss_distance_lunar < 1
ORDER BY ca.miss_distance_lunar ASC;
"""

df5 = pd.read_sql(select_query, engine)
df5 = df5.reset_index(drop=True)
df5.style.hide(axis="index")

In [42]:
# "15. Asteroids that came within 0.05 AU"
select_query = """
SELECT DISTINCT a.name, ca.close_approach_date, ca.astronomical
FROM close_approach_table ca
JOIN (SELECT DISTINCT id, name FROM asteroids_table) a
    ON ca.neo_reference_id = a.id
WHERE ca.astronomical <= 0.05
ORDER BY ca.astronomical ASC;
"""

df4 = pd.read_sql(select_query, engine)
df4 = df4.reset_index(drop=True)
df4.style.hide(axis="index")

# Streamlit

In [43]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\hp\miniconda3\lib\site-packages (1.59.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (7.1.4)
Requirement already satisfied: click<9,>=7.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\hp\appdata\roaming\python\python313\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging>=20 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette>=0.40.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (0.51.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (4.11.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\hp\miniconda3\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\hp\miniconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\hp\miniconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\hp\miniconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.23.0)
Requirement already satisfied: colorama in c:\users\hp\miniconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\hp\miniconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\hp\miniconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\miniconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\miniconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\miniconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\miniconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\miniconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\miniconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\miniconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.8.3)
Requirement already satisfied: sniffio>=1.1 in c:\users\hp\miniconda3\lib\site-packages (from anyio>=4.0.0->streamlit) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\miniconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\hp\miniconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hp\miniconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hp\miniconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\hp\miniconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.27.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in c:\users\hp\miniconda3\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)